import{a as $,S as q,N as O,P as x,M as T,K as D,b as l,A as N}from"./assets/vendor-B2Wr_42J.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const w of s.addedNodes)w.tagName==="LINK"&&w.rel==="modulepreload"&&n(w)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const j=document.querySelector(".burger-btn"),H=document.querySelector(".mob-menu-close-btn"),L=document.querySelector(".mob-menu"),U=window.matchMedia("(min-width: 768px)"),R=()=>{console.log("click on burger"),L.classList.add("is-open")},I=()=>{L.classList.remove("is-open")},F=e=>{e.matches&&I()},K=e=>{e.target.closest("a")!==null&&I()};L.addEventListener("click",K);j.addEventListener("click",R);H.addEventListener("click",I);U.addEventListener("change",F);const f=$.create({baseURL:"https://wedding-photographer.b.goit.study/api"}),V=async()=>{try{return(await f.get("feedbacks",{params:{limit:9,page:1}})).data}catch(e){console.log(e)}},_=async()=>{try{return(await f.get("categories")).data}catch(e){console.log(e)}},P=async({pageNumber:e=1,limit:t=9,sortName:o="title",categoryId:n}={})=>{try{return(await f.get("wedding-photos",{params:{page:`${e}`,limit:`${t}`,sortName:`${o}`,categoryId:n}})).data}catch(r){console.log(r)}},G=async({name:e,phone:t,message:o})=>{try{return await f.post("orders",{name:e,phone:t,message:o})}catch(n){console.log(n)}},A=document.querySelector(".feedbacks-list"),W=e=>e.map(({descr:t,name:o})=>`
       <li class="feedbacks-item swiper-slide">
       <div class="feedbacks-item-textual-wrapper">
          <p class="feedbacks-comments">
           ${t}
          </p>
          <p class="feedbacks-names">${o}</p>
        </div>
        </li>`).join(""),Y=async()=>{A.textContent="";try{const e=await V();A.insertAdjacentHTML("afterbegin",W(e.feedbacks))}catch(e){console.log(e)}};Y();new q(".swiper",{modules:[O,x,T,D],spaceBetween:24,speed:500,breakpoints:{320:{slidesPerView:1},768:{slidesPerView:3}},mousewheel:{forceToAxis:!0},keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".feedbacks-button-next",prevEl:".feedbacks-button-prev"},pagination:{el:".custom-swiper-pagination",type:"bullets",clickable:!0,dynamicBullets:!0}});const z=e=>{let t;l.fire({title:`${e} <br><b></b>`,timer:2e3,timerProgressBar:!0,didOpen:()=>{l.showLoading();const o=l.getPopup().querySelector("b");t=setInterval(()=>{o.textContent=`${l.getTimerLeft()}`},100)},willClose:()=>{clearInterval(t)}})},m=e=>{l.fire({position:"top-end",icon:"error",title:"Oops...",text:`${e}`,showConfirmButton:!1,timer:2e3})},C=document.querySelector(".loader"),M=()=>{C.classList.remove("visually-hidden")},u=()=>{C.classList.add("visually-hidden")},k=document.querySelector(".portfolio-buttons-list"),h=document.querySelector(".portfolio-gallery-list"),B=document.querySelector(".portfolio-button-load-more"),J=document.querySelector(".portfolio-uploaded-photo"),Q=document.querySelector(".portfolio-total-amount");B.disabled=!0;const X=e=>e.map(({_id:t,category:o})=>`
        <li data-id="${t}">
            <button type="button" class="portfolio-button" data-id="${t}">
                ${o}
            </button>
        </li>
        `).join(""),Z=async()=>{try{const e=await _();k.insertAdjacentHTML("beforeend",X(e))}catch(e){console.log(e)}};Z();let c=0,y=3,p=1,g,a=0;const E=(e,t)=>{J.textContent=e,Q.textContent=t},S=e=>e.map(({_id:t,img:o,title:n})=>`  
        <li class="portfolio-gallery-item" data-id="${t}">
            <img src="${o}" alt="${n}">
        </li>`).join(""),b=()=>{h.innerHTML="",c=0,p=1,y=3,g=null,a=0},i=e=>{B.disabled=e},ee=async()=>{b(),M(),i(!0);try{const e=await P({});if(c=e.totalItems,p+=e.weddingPhotos.length/y,a+=e.weddingPhotos.length,E(a,c),e.weddingPhotos.length===0)throw new Error("Empty array");h.insertAdjacentHTML("beforeend",S(e.weddingPhotos)),i(!1),u()}catch(e){console.log(e),m(e),b(),i(!0),u()}};ee();const v=(e,t)=>{if(e>=t)return z("NO MORE CONTENT"),i(!0),u(),!0},te=async()=>{if(M(),!v(a,c))try{const e=await P({pageNumber:p,limit:y,categoryId:g});if(a+=e.weddingPhotos.length,p+=1,E(a,c),h.insertAdjacentHTML("beforeend",S(e.weddingPhotos)),v(a,c))return;i(!1),u()}catch(e){console.log(e),m(e),i(!0),u()}};B.addEventListener("click",te);const oe=e=>{k.querySelector(".active").classList.remove("active"),e.classList.add("active")},re=async e=>{const t=e.target.closest("button");if(t){oe(t),i(!0),M(),b(),g=t.dataset.id;try{const o=await P({categoryId:g});if(c=o.totalItems,p+=o.weddingPhotos.length/y,a+=o.weddingPhotos.length,E(a,c),o.weddingPhotos.length===0)throw new Error("Empty array");if(h.insertAdjacentHTML("beforeend",S(o.weddingPhotos)),i(!1),v(a,c)){i(!0);return}u()}catch(o){console.log(o),m(o),i(!0),u()}}};k.addEventListener("click",re);new N(".accordion-container",{duration:400,showMultiple:!0,onOpen:function(e){console.log(e)}});const ne=e=>{let t;l.fire({html:`${e} <br><b></b>`,timer:3e3,timerProgressBar:!0,didOpen:()=>{l.showLoading(),t=setInterval(()=>{},100)},willClose:()=>{clearInterval(t)}})},se=new URL("/project-CodeNex2/assets/success-modal-DTfRJMzB.jpg",import.meta.url).href,d=document.querySelector(".contacts-form"),ae=`<div class="modal_success">
  <div class="modal_success-container">
    <div class="modal_success-content-wrapper">
      <h2>Thank You for Your Inquiry!</h2>
      <div class="modal_success-img-container">
        <img src=${se} alt="wedding" />
      </div>
      <p>
        I have received your message and I'm so excited about your interest! I
        will get in touch with you within 24-48 hours to discuss the details of
        your wedding day. In the meantime, feel free to browse my portfolio or
        follow me on Instagram for more inspiration.
      </p>
    </div>
  </div>
</div>`,ie=({name:e,phone:t,message:o})=>{e===""&&d.elements.name.classList.add("is-error"),t===""&&d.elements.phone.classList.add("is-error"),o===""&&d.elements.message.classList.add("is-error")},ce=async e=>{e.preventDefault();const t=new FormData(d),o={name:t.get("name").trim(),phone:t.get("phone").trim(),message:t.get("message").trim()};if(o.name===""||o.phone===""||o.message===""){ie(o),m("The field is empty!");return}try{(await G({name:o.name,phone:o.phone,message:o.message})).status===201&&(ne(ae),d.reset())}catch(n){console.log(n),m(n)}},le={},de=e=>{le[e.target.name]=e.target.value,e.target.value.trim()!==""&&e.target.classList.remove("is-error")};d.addEventListener("submit",ce);d.addEventListener("input",de);
//# sourceMappingURL=index.js.map
