import{a as q,S as A,N as O,P as x,M as T,K as D,b as l}from"./assets/vendor-D-vJw_Y6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const n of s)if(n.type==="childList")for(const w of n.addedNodes)w.tagName==="LINK"&&w.rel==="modulepreload"&&r(w)}).observe(document,{childList:!0,subtree:!0});function o(s){const n={};return s.integrity&&(n.integrity=s.integrity),s.referrerPolicy&&(n.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?n.credentials="include":s.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(s){if(s.ep)return;s.ep=!0;const n=o(s);fetch(s.href,n)}})();const N=document.querySelector(".burger-btn"),j=document.querySelector(".mob-menu-close-btn"),L=document.querySelector(".mob-menu"),H=window.matchMedia("(min-width: 768px)"),U=()=>{console.log("click on burger"),L.classList.add("is-open")},P=()=>{L.classList.remove("is-open")},R=e=>{e.matches&&P()},F=e=>{e.target.closest("a")!==null&&P()};L.addEventListener("click",F);N.addEventListener("click",U);j.addEventListener("click",P);H.addEventListener("change",R);const f=q.create({baseURL:"https://wedding-photographer.b.goit.study/api"}),K=async()=>{try{return(await f.get("feedbacks",{params:{limit:9,page:1}})).data}catch(e){console.log(e)}},V=async()=>{try{return(await f.get("categories")).data}catch(e){console.log(e)}},I=async({pageNumber:e=1,limit:t=9,sortName:o="title",categoryId:r}={})=>{try{return(await f.get("wedding-photos",{params:{page:`${e}`,limit:`${t}`,sortName:`${o}`,categoryId:r}})).data}catch(s){console.log(s)}},_=async({name:e,phone:t,message:o})=>{try{return await f.post("orders",{name:e,phone:t,message:o})}catch(r){console.log(r)}},C=document.querySelector(".feedbacks-list"),G=e=>e.map(({descr:t,name:o})=>`
       <li class="feedbacks-item swiper-slide">
       <div class="feedbacks-item-textual-wrapper">
          <p class="feedbacks-comments">
           ${t}
          </p>
          <p class="feedbacks-names">${o}</p>
        </div>
        </li>`).join(""),W=async()=>{C.textContent="";try{const e=await K();C.insertAdjacentHTML("afterbegin",G(e.feedbacks))}catch(e){console.log(e)}};W();new A(".swiper",{modules:[O,x,T,D],spaceBetween:24,speed:500,breakpoints:{320:{slidesPerView:1},768:{slidesPerView:3}},mousewheel:{forceToAxis:!0},keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".feedbacks-button-next",prevEl:".feedbacks-button-prev"},pagination:{el:".custom-swiper-pagination",type:"bullets",clickable:!0,dynamicBullets:!0}});const Y=e=>{let t;l.fire({title:`${e} <br><b></b>`,timer:2e3,timerProgressBar:!0,didOpen:()=>{l.showLoading();const o=l.getPopup().querySelector("b");t=setInterval(()=>{o.textContent=`${l.getTimerLeft()}`},100)},willClose:()=>{clearInterval(t)}})},m=e=>{l.fire({position:"top-end",icon:"error",title:"Oops...",text:`${e}`,showConfirmButton:!1,timer:2e3})},$=document.querySelector(".loader"),M=()=>{$.classList.remove("visually-hidden")},u=()=>{$.classList.add("visually-hidden")},k=document.querySelector(".portfolio-buttons-list"),h=document.querySelector(".portfolio-gallery-list"),B=document.querySelector(".portfolio-button-load-more"),z=document.querySelector(".portfolio-uploaded-photo"),J=document.querySelector(".portfolio-total-amount");B.disabled=!0;const Q=e=>e.map(({_id:t,category:o})=>`
        <li data-id="${t}">
            <button type="button" class="portfolio-button" data-id="${t}">
                ${o}
            </button>
        </li>
        `).join(""),X=async()=>{try{const e=await V();k.insertAdjacentHTML("beforeend",Q(e))}catch(e){console.log(e)}};X();let c=0,y=3,p=1,g,a=0;const E=(e,t)=>{z.textContent=e,J.textContent=t},S=e=>e.map(({_id:t,img:o,title:r})=>`  
        <li class="portfolio-gallery-item" data-id="${t}">
            <img src="${o}" alt="${r}">
        </li>`).join(""),b=()=>{h.innerHTML="",c=0,p=1,y=3,g=null,a=0},i=e=>{B.disabled=e},Z=async()=>{b(),M(),i(!0);try{const e=await I({});if(c=e.totalItems,p+=e.weddingPhotos.length/y,a+=e.weddingPhotos.length,E(a,c),e.weddingPhotos.length===0)throw new Error("Empty array");h.insertAdjacentHTML("beforeend",S(e.weddingPhotos)),i(!1),u()}catch(e){console.log(e),m(e),b(),i(!0),u()}};Z();const v=(e,t)=>{if(e>=t)return Y("NO MORE CONTENT"),i(!0),u(),!0},ee=async()=>{if(M(),!v(a,c))try{const e=await I({pageNumber:p,limit:y,categoryId:g});if(a+=e.weddingPhotos.length,p+=1,E(a,c),h.insertAdjacentHTML("beforeend",S(e.weddingPhotos)),v(a,c))return;i(!1),u()}catch(e){console.log(e),m(e),i(!0),u()}};B.addEventListener("click",ee);const te=e=>{k.querySelector(".active").classList.remove("active"),e.classList.add("active")},oe=async e=>{const t=e.target.closest("button");if(t){te(t),i(!0),M(),b(),g=t.dataset.id;try{const o=await I({categoryId:g});if(c=o.totalItems,p+=o.weddingPhotos.length/y,a+=o.weddingPhotos.length,E(a,c),o.weddingPhotos.length===0)throw new Error("Empty array");if(h.insertAdjacentHTML("beforeend",S(o.weddingPhotos)),i(!1),v(a,c)){i(!0);return}u()}catch(o){console.log(o),m(o),i(!0),u()}}};k.addEventListener("click",oe);const re=e=>{let t;l.fire({html:`${e} <br><b></b>`,timer:3e3,timerProgressBar:!0,didOpen:()=>{l.showLoading(),t=setInterval(()=>{},100)},willClose:()=>{clearInterval(t)}})},se=new URL("/project-CodeNex2/assets/success-modal-DTfRJMzB.jpg",import.meta.url).href,d=document.querySelector(".contacts-form"),ne=`<div class="modal_success">
  <div class="modal_success-container">
    <div class="modal_success-content-wrapper">
      <h2>Thank You for Your Inquiry!</h2>
      <div class="modal_success-img-container">
        <img src=${se} alt="wedding" />
      </div>
      <p>
        I have received your message and I'm so excited about your interest! I
        will get in touch with you within 24-48 hours to discuss the details of
        your wedding day. In the meantime, feel free to browse my portfolio or
        follow me on Instagram for more inspiration.
      </p>
    </div>
  </div>
</div>`,ae=({name:e,phone:t,message:o})=>{if(e===""){const r=d.elements.name;r.classList.add("is-error"),console.log(r)}if(t===""){const r=d.elements.phone;r.classList.add("is-error"),console.log(r)}if(o===""){const r=d.elements.message;r.classList.add("is-error"),console.log(r)}},ie=async e=>{e.preventDefault();const t=new FormData(d),o={name:t.get("name").trim(),phone:t.get("phone").trim(),message:t.get("message").trim()};if(o.name===""||o.phone===""||o.message===""){ae(o),m("The field is empty!");return}try{(await _({name:o.name,phone:o.phone,message:o.message})).status===201&&(re(ne),d.reset())}catch(r){console.log(r),m(r)}},ce={},le=e=>{ce[e.target.name]=e.target.value,e.target.value.trim()!==""&&e.target.classList.remove("is-error")};d.addEventListener("submit",ie);d.addEventListener("input",le);
//# sourceMappingURL=index.js.map
